import Head from "next/head";
import {
  Container,
  TopBar,
  Option,
  OptionOne,
  Icones,
  TopBarWrite,
  Body,
  Imagem,
  Text,
  Title,
  Button,
  TopBarIcons,
  IconeInstagram,
  StyledLink,
} from "../components/mystyles2";
import Cards from "../components/cards";
import Link from "next/link";

export default function Home() {
  return (
    <Container>
      <TopBar>
        <TopBarWrite>
          <OptionOne>SÓCIO VOLUNTÁRIO</OptionOne>
          <Option>LOJA</Option>
          <Option>NOSSAS AÇÕES</Option>
          <Option>DOAR</Option>
          <Option>QUEM SOMOS</Option>
          <Option>FALE CONOSCO</Option>
        </TopBarWrite>
        <TopBarIcons>
          <StyledLink>
            <Icones src="/images/pesquisa.png" />
          </StyledLink>
          <StyledLink>
            <Icones src="/images/carrinho.png" />
          </StyledLink>
          <StyledLink
            href="https://www.instagram.com/olhosdobem.br"
            target={"_blank"}
          >
            <IconeInstagram src="/images/instagram.png" />
          </StyledLink>
        </TopBarIcons>
      </TopBar>
      <Body>
        <Text>
          <Title> OLHOS DO BEM </Title>
          <br />
          <br />
          A associação sem fins lucrativos “Olhos do bem” localizada na cidade
          de Franca – SP, atua no combate à fome e desenvolvimento da
          comunidade, através de projetos socioeducacionais efetuados na região.
          <br />
          <Button>QUERO AJUDAR!</Button>
          {/* Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus in qui, inventore quis expedita facere quo ab veniam itaque magnam architecto tempore? Reprehenderit quae vel ipsam pariatur velit hic ullam?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus natus deleniti blanditiis hic consectetur, doloribus error nesciunt placeat vel ullam porro inventore consequatur quae sint recusandae non ab qui modi!
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis sunt veniam explicabo, tempore voluptatem maxime repellat vero laborum minima soluta. Voluptatibus, debitis? Eveniet alias rem odio animi maiores, necessitatibus iste.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, reprehenderit voluptate temporibus quis veniam itaque ea culpa aperiam totam autem, eaque eos. Obcaecati ea cumque consectetur, quis ullam illo est!
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat, sit veritatis? Doloribus at, minus quod quaerat nobis deserunt dolorem nisi earum nemo laudantium modi sint. Ea facilis expedita architecto est? */}
        </Text>
        <Imagem src="/images/OlhosDoBem_LOGO.jpg" />
      </Body>
      {/* <Button>QUERO AJUDAR!</Button> */}
    </Container>

    /*<Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description>

        <Cards />
      </Main>
    </Container>
    */
  );
}
